### ISSUE TITLE
 TemplateNotFound: export.html

### ISSUE THREAD

**Issue by cumulus13** [pyrocat101/moo#21]
Traceback (most recent call last):
      File "/sdk/anaconda2/lib/python2.7/site-packages/moo/__init__.py", line 227, in main
        export_files(files, options)
      File "/sdk/anaconda2/lib/python2.7/site-packages/moo/__init__.py", line 175, in export_files
        template = env.get_template('export.html')
      File "/sdk/anaconda2/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_template
        return self._load_template(name, self.make_globals(globals))
      File "/sdk/anaconda2/lib/python2.7/site-packages/jinja2/environment.py", line 804, in _load_template
        template = self.loader.load(self, name, globals)
      File "/sdk/anaconda2/lib/python2.7/site-packages/jinja2/loaders.py", line 115, in load
        source, filename, uptodate = self.get_source(environment, name)
      File "/sdk/anaconda2/lib/python2.7/site-packages/jinja2/loaders.py", line 189, in get_source
        raise TemplateNotFound(template)
    TemplateNotFound: export.html

what minimum requirements for moo ?

**Comment by cumulus13** [comment]
its ok, i copy from github to my python lib
copy -r /projects/moo/moo/templates /sdk/anaconda2/lib/python2.7/site-packages/moo/

:)
